#!/usr/bin/env bash
# you no love me
NO_LOVE='rm /var/run/myscript.pid; exit $?'

echo $$ > "/var/run/myscript.pid"

trap 'echo "I hate the kill command"; '"$NO_LOVE" SIGTERM

trap 'echo "Y U no love me?!"' SIGINT

trap ''"$NO_LOVE" SIGQUIT


while true; do
  echo "To infinity and beyond"
done
